### ISSUE TITLE
Invite.createInvite failing when specifying a targetUser

### ISSUE THREAD

**Issue by c-shimmer** [discordjs/guide#1062]
### Describe the bug

The following code seems to be causing an error within discord.js:

Sample code:
```
const myStageChannel: StageChannel = /* ... */;
const myUser: User = await guild.members.fetch({user: myUserId});
const channelInvite: Invite = await myStageChannel.createInvite({
    targetUser: myUser
});
```

Corresponding error stack:
```
DiscordAPIError: Invalid Form Body
target_user_id: Invalid target user id
    at RequestHandler.execute (/REDACTED/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/REDACTED/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at GuildInviteManager.create (/REDACTED/node_modules/discord.js/src/managers/GuildInviteManager.js:185:20)
    at DiscordBot.setupStageChannel (/REDACTED/discord-bot/src/discord-bot.ts:79:53)
    at /REDACTED/discord-bot/src/index.ts:68:31
```

The failing code in question seems to be the following:

`node_modules/discord.js/src/managers/GuildInviteManager.js`
```
**
   * Create an invite to the guild from the provided channel.
   * @param {GuildInvitableChannelResolvable} channel The options for creating the invite from a channel.
   * @param {CreateInviteOptions} [options={}] The options for creating the invite from a channel.
   * @returns {Promise<Invite>}
   * @example
   * // Create an invite to a selected channel
   * guild.invites.create('599942732013764608')
   *   .then(console.log)
   *   .catch(console.error);
   */
  async create(
    channel,
    { temporary = false, maxAge = 86400, maxUses = 0, unique, targetUser, targetApplication, targetType, reason } = {},
  ) {
    const id = this.guild.channels.resolveId(channel);
    if (!id) throw new Error('GUILD_CHANNEL_RESOLVE');

    const invite = await this.client.api.channels(id).invites.post({
      data: {
        temporary,
        max_age: maxAge,
        max_uses: maxUses,
        unique,
        target_user_id: this.client.users.resolveId(targetUser),  // <--- HERE
        target_application_id: targetApplication?.id ?? targetApplication?.applicationId ?? targetApplication,
        target_type: targetType,
      },
      reason,
    });
    return new Invite(this.client, invite);
  }
```

### To Reproduce

See steps above. For version: `package-lock.json`

```
"node_modules/discord.js": {
      "version": "13.6.0",
      "resolved": "https://registry.npmjs.org/discord.js/-/discord.js-13.6.0.tgz",
      "integrity": "sha512-tXNR8zgsEPxPBvGk3AQjJ9ljIIC6/LOPjzKwpwz8Y1Q2X66Vi3ZqFgRHYwnHKC0jC0F+l4LzxlhmOJsBZDNg9g==",
      "dependencies": {
        "@discordjs/builders": "^0.11.0",
        "@discordjs/collection": "^0.4.0",
        "@sapphire/async-queue": "^1.1.9",
        "@types/node-fetch": "^2.5.12",
        "@types/ws": "^8.2.2",
        "discord-api-types": "^0.26.0",
        "form-data": "^4.0.0",
        "node-fetch": "^2.6.1",
        "ws": "^8.4.0"
      },
      "engines": {
        "node": ">=16.6.0",
        "npm": ">=7.0.0"
      }
    },
```

### Device (please complete the following information)

macOS + nodeJS

**Comment by c-shimmer** [comment]
(Filed in the wrong repository, I migrated this issue to https://github.com/discordjs/discord.js/issues/7675
