### ISSUE TITLE
Authorization code grant flow error in provided example

### ISSUE THREAD

**Issue by petepi3** [discordjs/guide#1172]
### Describe the bug

https://discordjs.guide/oauth2/#authorization-code-grant-flow

In code snippet number three, undici request function requires either a string or a buffer object for the body object and current code throws an error.

`
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array
    at new NodeError (node:internal/errors:372:5)
    at Function.byteLength (node:buffer:735:11)
    at AsyncWriter.write (/home/petepi/LineApp/node_modules/undici/lib/client.js:1611:24)
    at writeIterable (/home/petepi/LineApp/node_modules/undici/lib/client.js:1572:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

Changing line 30 as follows:

`
				}).toString(),
`
Provides a string and fixes the issue.

### To Reproduce

Follow the guide on:
https://discordjs.guide/oauth2/#authorization-code-grant-flow

### Device (please complete the following information)

WSL 10.0.19041.1566 running ubuntu 20.04 LTS
NodeJS v16.15.1
Undici v5.7.0

**Comment by Juoper** [comment]
Look at my pull request i solved the problem #1235

**Comment by GalaxyDinoDragonYT** [comment]
@Juoper Using your pull request, I'm getting `SyntaxError: Unexpected token , in JSON at position 3` at `JSON.parse(fullBody)` (index.js line 11)

**Comment by Orangenal-name** [comment]
thanks for your help mysterious stranger!
