### ISSUE TITLE
Bot crashes after a while for no clear reason?

### ISSUE THREAD

**Issue by tigerzo** [discordjs/guide#135]
My bot works fine and then after a while it crashed because of an error. I don't know where to look to fix this error. 
Is this an error with discordjs itself? I'd like to know. here's an error.

events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Commando.emit (events.js:171:17)
    at WebSocketConnection.onError (G:\RustBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (G:\RustBot\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (G:\RustBot\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (G:\RustBot\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (G:\RustBot\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

**Comment by Dev-Yukine** [comment]
No thats not an issue with d.js rather then an issue with you not adding an event listener for the `error` event, if you want to know how to fix it see https://github.com/discordjs/discord.js/issues/2523

**Comment by tigerzo** [comment]
> No thats not an issue with d.js rather then an issue with you not adding an event listener for the `error` event, if you want to know how to fix it see [discordjs/discord.js#2523](https://github.com/discordjs/discord.js/issues/2523)

Thanks I'll try this :)

**Comment by tigerzo** [comment]
@Dev-Yukine I'd like to thank you for linking me to that page, I tried `commando.on('error', console.error);` and that seems to fix my issue I believe. bot will throw an error saying it lost connection trying to fetch the api and it restarts or whatever (haven't looked close), which works for me. I don't think I can fix it not being able to fetch the api sometimes.. dunno why it loses connection 😆

**Comment by ThatTonybo** [comment]
@tigerzo I *think* the Discord API just randomly disconnects at times, I've ran into my bots disconnecting and resume after about 12 hours of being logged in while I've been making my API wrapper, you can't avoid it I don't think.
