### ISSUE TITLE
Can not run it 

### ISSUE THREAD

**Issue by YlNGYANG** [discordjs/guide#170]
if i run 

yarn serve

i get this error:

Error: custom keyword definition is invalid: data/errors should be boolean
    at Ajv.addKeyword (E:\Desktop\Documentation\guide\node_modules\webpack\node_modules\ajv\lib\keyword.js:65:13)
    at module.exports (E:\Desktop\Documentation\guide\node_modules\ajv-errors\index.js:10:7)
    at Object.<anonymous> (E:\Desktop\Documentation\guide\node_modules\webpack\node_modules\schema-utils\src\validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Danktuary** [comment]
Could you provide more info, like your OS, Node/Yarn version, and anything else that's notable? I cloned it and installed the deps and running `yarn serve` seems to work fine.

**Comment by YlNGYANG** [comment]
OS: Windows 10
Node Version: 10.13.0
yarn version: 1.13.0
npm version: 6.7.0

**Comment by YlNGYANG** [comment]
i have run  

npm install 

first and then used 

yarn serve

**Comment by Danktuary** [comment]
I can't seem to reproduce it then. I'm on Windows 10, Node v10.15 (also tried on 8.11), Yarn 1.9.4, and npm 6.4.1. Maybe delete the folder and try again?

**Comment by YlNGYANG** [comment]
maybe it is Eslint related?
I have deleted and installed again still same problem

**Comment by YlNGYANG** [comment]
$ yarn install
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-aqua@4.4.1" has incorrect peer dependency "babel-eslint@^9.0.0".
warning " > eslint-config-aqua@4.4.1" has incorrect peer dependency "eslint@^5.6.0".
warning " > eslint-plugin-vue@5.1.0" has incorrect peer dependency "eslint@^5.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@4.0.3" has incorrect peer dependency "eslint@^5.0.0".


maybe cause of this warnings?

**Comment by YlNGYANG** [comment]
oh ... using npm install it failed but with yarn install it is working

**Comment by amishshah** [comment]
See https://github.com/webpack/webpack/issues/8768
