### ISSUE TITLE
Inventory command Doesn't work [ Currency System ]

### ISSUE THREAD

**Issue by DiljitSandhuDev** [discordjs/guide#194]
I had followed the tutorial and made currency system, but only the inventory command doesn't worked for me, here's the log:
`(node:15524) UnhandledPromiseRejectionWarning: Error: Include unexpected. Element has to be either a Model, an Association or an object.
    at Function._conformInclude ({{path}}\node_modules\sequelize\lib\model.js:390:11)
    at options.include.options.include.map.include ({{path}}\node_modules\sequelize\lib\model.js:326:59)
    at Array.map (<anonymous>)
    at Function._conformOptions ({{path}}\node_modules\sequelize\lib\model.js:326:39)
    at Function._baseMerge ({{path}}\node_modules\sequelize\lib\model.js:792:10)
    at Function._defaultsOptions ({{path}}\node_modules\sequelize\lib\model.js:823:31)
    at Function._injectScope ({{path}}\node_modules\sequelize\lib\model.js:3104:10)
    at Promise.try ({{path}}\node_modules\sequelize\lib\model.js:1697:12)
    at tryCatcher ({{path}}\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try ({{path}}\node_modules\bluebird\js\release\method.js:39:29)
    at Function.findAll ({{path}}\node_modules\sequelize\lib\model.js:1696:23)
    at model.Users.getItems ({{path}}\dbObjects.js:31:19)
    at Client.client.on ({{path}}\app.js:51:28)
(node:15524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
_I've replace actual path with {{path}}_

Thanks in advance!

**Comment by Lewdcario** [comment]
Hello, please refer to the [following issue](https://github.com/sequelize/sequelize/issues/10613) for an explanation for your issue. To put it simply, you are on the wrong version of sequelize (which also does not find `#findByPrimary`, it uses `#findByPk`/`#findOne` instead). Please update to latest and try again, with the [following link](https://github.com/discordjs/guide/blob/master/code-samples/sequelize/currency/app.js#L50), since the guide has an error with consistency right now.
