### ISSUE TITLE
return process.dlopen different node js versions crash at startup

### ISSUE THREAD

**Issue by Millie290** [discordjs/guide#211]
Hi i've got an issue with canvas on a bot and i don't know why so if someone can help me it will be very nice thanks :

pi@raspberrypi:~/BOTS/discord-bot-Fiskou-MiMillie $ node bot.js
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/pi/BOTS/discord-bot-Fiskou-MiMillie/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/BOTS/discord-bot-Fiskou-MiMillie/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

node.js version v10.15.3
npm version 6.4.1
OS raspbian

**Comment by vladfrangu** [comment]
You'll want to rebuild your modules by reinstalling them if you upgrade or downgrade your node.js version. You can do this the easy way by just running `npm i` again

**Comment by Millie290** [comment]
> 
> 
> You'll want to rebuild your modules by reinstalling them if you upgrade or downgrade your node.js version. You can do this the easy way by just running `npm i` again

'so npm i canvas' reinstalling them and i've used npm rebuild

**Comment by ADACosmos** [comment]
any fix?
