### ISSUE TITLE
I get this message now ;(

### ISSUE THREAD

**Issue by sayantan300** [discordjs/guide#467]
TypeError: this.commands.filterArray is not a function
2020-08-28T05:31:11.347853+00:00 app[worker.1]:     at CommandRegistry.findCommands (/app/node_modules/discord.js-commando/src/registry.js:438:41)
2020-08-28T05:31:11.347855+00:00 app[worker.1]:     at CommandDispatcher.matchDefault (/app/node_modules/discord.js-commando/src/dispatcher.js:254:34)
2020-08-28T05:31:11.347855+00:00 app[worker.1]:     at CommandDispatcher.parseMessage (/app/node_modules/discord.js-commando/src/dispatcher.js:238:21)
2020-08-28T05:31:11.347856+00:00 app[worker.1]:     at CommandDispatcher.handleMessage (/app/node_modules/discord.js-commando/src/dispatcher.js:114:18)
2020-08-28T05:31:11.347857+00:00 app[worker.1]:     at CommandoClient.<anonymous> (/app/node_modules/discord.js-commando/src/client.js:68:51)
2020-08-28T05:31:11.347858+00:00 app[worker.1]:     at CommandoClient.emit (events.js:315:20)
2020-08-28T05:31:11.347859+00:00 app[worker.1]:     at CommandoClient.EventEmitter.emit (domain.js:483:12)
2020-08-28T05:31:11.347859+00:00 app[worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-08-28T05:31:11.347861+00:00 app[worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-08-28T05:31:11.347862+00:00 app[worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

**Comment by almostSouji** [comment]
Collection#filterArray is a [v11 method](https://discord.js.org/#/docs/main/v11/class/Collection?scrollTo=filterArray) and does not exist on v12.
This error points to you using Commando for v11 and discord.js v12, which are incompatible.

Please stop using this issue tracker as replacement for the discord server. The issue tracker is only for bug reports, feature requests and improvements to the guide.

**Comment by sayantan300** [comment]
But I'm banned on discordjs server and idk how to get unbanned ;(

**Comment by sayantan300** [comment]
@almostSouji

**Comment by almostSouji** [comment]
And if you keep using github as discord replacement - including the spamming of messages you will soon be banned here too.
