### ISSUE TITLE
I got an error with the API while fetching messages

### ISSUE THREAD

**Issue by Alonely0** [discordjs/guide#471]
I was running this code that in theory had to tell me if there are any new messages.
```js
const Discord = require("discord.js");
const bot = new Discord.Client();

bot.on("ready", () => {
  console.log(`Logged in as ${bot.user.tag}!`);
});

setInterval(() => {
  let channel = bot.channels.cache.get("asadasadasadas");
  channel.messages.fetch({ limit: 1 }).then((messages) => {
    let cache = [];
    let lastMessage = messages.first();
    if (lastMessage.id != cache.pop()) {
      console.log(lastMessage.content);
      cache.push(lastMessage.id);
    }
  });
}, 1000);

bot.login("asadasadasadas");

```
Error:
```err
(node:58932) UnhandledPromiseRejectionWarning: TypeError: Object.entries(...).filter(...).flatMap is not a function
    at new APIRequest (/home/dog/Desktop/test/node_modules/discord.js/src/rest/APIRequest.js:23:10)
    at RESTManager.request (/home/dog/Desktop/test/node_modules/discord.js/src/rest/RESTManager.js:52:24)
    at Proxy.options (/home/dog/Desktop/test/node_modules/discord.js/src/rest/APIRouter.js:30:19)
    at MessageManager._fetchMany (/home/dog/Desktop/test/node_modules/discord.js/src/managers/MessageManager.js:139:75)
    at MessageManager.fetch (/home/dog/Desktop/test/node_modules/discord.js/src/managers/MessageManager.js:67:86)
    at Timeout.setInterval [as _onTimeout] (/home/dog/Desktop/test/index.js:10:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:58932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:58932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I was using discord.js v12.3 on Linux, exactly KDE neon that is an Ubuntu-based distribution.

**Comment by zaida04** [comment]
Please update your node version, and it would be best to move any intervals such as that in your ready event in order to ensure you have a logged in client. In addition to that, fetching once a second sounds like heavy api abuse.

**Comment by Alonely0** [comment]
I change it for testing, I had to 5 minutes. I use node 12

**Comment by Alonely0** [comment]
@zaida04

**Comment by almostSouji** [comment]
[Array#flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) was introduced in node 11.0.0.

Discord.js version 12 requires node 12.0.0+ to work properly, please update your node version.

--- 

besides the point doing this on an interval is entirely obsolete (and the implementation wrong at that, seeing that your "cache" is completely re-instantiated every second. Discord.js attaches the last message to the channel in [TextChannel#lastMessage](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=lastMessage).
