### ISSUE TITLE
CommandHandlerError

### ISSUE THREAD

**Issue by incamilo** [discordjs/guide#670]
EventHandlerErrorConsole:

(node:2247) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
    at Object.execute (/storage/emulated/0/Discord/Bots/test/events/ready.js:6:18)
    at Client.<anonymous> (/storage/emulated/0/Discord/Bots/test/bot.js:21:44)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/storage/emulated/0/Discord/Bots/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
