### ISSUE TITLE
node-fetch v3 doesn't support require()

### ISSUE THREAD

**Issue by Empi3** [discordjs/guide#882]
Page https://discordjs.guide/additional-info/rest-api.html specifies importing node-fetch as such

> const fetch = require('node-fetch');

but the latest version of node-fetch doesn't support require().

`Error [ERR_REQUIRE_ESM]: require() of ES Module <cut>\Bot\node_modules\node-fetch\src\index.js from <cut>\Bot\commands\oggi.js not supported.
Instead change the require of index.js in <cut>\Bot\commands\oggi.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (<cut>\Bot\commands\oggi.js:2:15)
    at Object.<anonymous> (<cut>\Bot\index.js:14:18) {
  code: 'ERR_REQUIRE_ESM'`

import fetch from "node-fetch"; should be used, but that causes a series of different problems.

**Comment by DTrombett** [comment]
[This](https://discordjs.guide/additional-info/rest-api.html#making-http-requests-with-node) should probably be changed to install the v2 or change the suggested library.

**Comment by Empi3** [comment]
I used this line suggested in node-fetch documentation. https://github.com/node-fetch/node-fetch#installation

`const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));`

works fine.

**Comment by Megatank58** [comment]
#883 fixes this
