### ISSUE TITLE
Error when deploying node js app

### ISSUE THREAD

**Issue by ADACosmos** [discordjs/guide#955]
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/lunechai/nodevenv/welcomeimagebot/14/lib/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/lunechai/nodevenv/welcomeimagebot/14/lib/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

So this is the error. It works fine on my vscode.
 This discord bot only have 2 package that need to be installed which are 
1) discord.js
2) canvas.js

I don't know what is the error. The node js that i'm using is 14.18 and it is the same on the platform that i want to deply. 
Any help? :c

**Comment by J-Human** [comment]
Hey there. 

You seem to be on Linux. But anyways, do you have the newest version of GCC installed? FYI Canvas needs a C++ compiler since it's a native Node addon. If you don't have GCC, just install it, e.g. `sudo apt-get install build-essential gcc`. Referencing `https://github.com/FoldingAtHome/fah-issues/issues/1147#issuecomment-134731211` here, you need GCC v5.1.0/libstdc++.so.6.0.21 to use the ABI version the binary is asking for.
