### ISSUE TITLE
BUG DISCORD.JS

### ISSUE THREAD

**Issue by LeRomino** [discordjs/guide#994]
ErrorCaptureStackTrace(err);
    ^

I use a music system on my bot discord but there is an error!
TypeError [ERR_INVALID_ARG_TYPE]: The "body" argument must be of type function or an instance of Blob, ReadableStream, WritableStream, Stream, Iterable, AsyncIterable, or Promise or { readable, writable } pair. Received null
    at new NodeError (node:internal/errors:371:5)
    at duplexify (node:internal/streams/duplexify:199:9)
    at Function.Duplex.from (node:internal/streams/duplex:143:10)
    at pipelineImpl (node:internal/streams/pipeline:235:22)
    at pipeline (node:internal/streams/pipeline:146:10)
    at new j (/home/container/node_modules/@discordjs/voice/dist/index.js:8:15591)
    at je (/home/container/node_modules/@discordjs/voice/dist/index.js:8:17218)
    at StreamDispatcher.createStream (/home/container/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:116:62)
    at Queue.<anonymous> (/home/container/node_modules/discord-player/dist/Structures/Queue.js:697:46)
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by vitorlops** [comment]
Here are issues from the guide, I guess.
Try using [GitHub Discussions](https://github.com/discordjs/guide/discussions) or the [discord server](https://discord.gg/djs).
